export default {
  brandId: 'objectId',
  categoryIds: ['objectId'],
  description: 'string',
  hasVariants: 'boolean',
  mediaIds: ['objectId'],
  productType: 'simple | variable | digital | bundle',
  seo: {
    description: 'string',
    keywords: ['string'],
    title: 'string',
  },
  shipping: {
    height: 'number',
    length: 'number',
    weight: 'number',
    width: 'number',
  },
  shortDescription: 'string',
  slug: 'string',
  status: 'draft | active | archived',
  tagIds: ['objectId'],
  tags: ['string'],
  thumbnail: 'objectId',
  title: 'string',
};
